# Version is Deprecated since new docker-compose
#version: '3.8'

services:
  bot:
    container_name: "CexBot"
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
        reservations:
          cpus: '0.2'
          memory: '128M'
